AllCops:
  TargetRubyVersion: 3.1
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - 'sig/**/*'

plugins:
  - rubocop-rspec
  - rubocop-performance
  - rubocop-rake

Layout/LineLength:
  Max: 120

Style/Documentation:
  Enabled: false

Naming/FileName:
  Exclude:
    - 'lib/rspec-rewind.rb'

Metrics/AbcSize:
  Max: 30

Metrics/ClassLength:
  Max: 400

Metrics/MethodLength:
  Max: 60

Metrics/CyclomaticComplexity:
  Max: 15

Metrics/PerceivedComplexity:
  Max: 15

Metrics/ParameterLists:
  Max: 8

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'

Lint/ConstantDefinitionInBlock:
  Exclude:
    - 'spec/**/*.rb'

RSpec/ExampleLength:
  Max: 20

RSpec/MultipleExpectations:
  Max: 6

RSpec/InstanceVariable:
  Enabled: false

RSpec/LeakyConstantDeclaration:
  Enabled: false
